### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by hexLucifer**
Replaced stack of replaceAll with regex.

### CODE REVIEW

**Comment by cakedbake** [comment]
Does it preserve capitalization?

**Review by hexLucifer — COMMENTED** [review]
It does now

**Comment by cakedbake** [comment]
It outputs `ReGrEt` when given `ReGeX`, which is not faithful to the original (`ReGeX` -> `ReGreT`).

**Comment by cakedbake** [comment]
Looking back at the previous pull requests you've made, I'm starting to doubt your competence as a professional programmer. Your pull requests look like they were made by a small boy, or an LLM. I don't want a small boy to write code for me. I keep my code up to my own (lackluster, but still present) standards.

**Comment by hexLucifer** [comment]
> It outputs `ReGrEt` when given `ReGeX`, which is not faithful to the original (`ReGeX` -> `ReGreT`).

Kinda not my problem

**Comment by cakedbake** [comment]
No worries, it absolutely **is** your problem seeing as **you** are the one who opened this pull request.

**Comment by hexLucifer** [comment]
> No worries, it absolutely **is** your problem seeing as **you** are the one who opened this pull request.

Considering I just closed said pull request, it is no longer my problem

**Comment by cakedbake** [comment]
I'll make it your problem.

**Comment by hexLucifer** [comment]
OwO

**Pull request closed without merging**
